server:
  port: 8088

spring:
  application:
    name: auth-service

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

app:
  qr:
    secret: ${APP_QR_SECRET:"TnsLD53NKeFsHhZ73ojREN9XLT8dIuuvmeSh/f3FU2KF7q4m11nf/PJivEuplO9U4tZDUW0JPPByW2VHOU2HMQ=="}
    token_ttl_seconds: 600   # QR token TTL (seconds) e.g. 10 minutes
  session:
    ttl-seconds: 21600       # session TTL for Redis
    token-ttl-seconds: 1800  # session JWT lifetime (seconds)

#  session:
#    ttl-seconds: 21600         # 6 hours
#    token-ttl-seconds: 1800    # session JWT lifetime (30 minutes)
#  keys:
#    # file paths (can be absolute or classpath:)
#    session-private-key-file: ${APP_SESSION_PRIVATE_KEY:/run/secrets/auth_session_private.pem}
#    session-public-key-file:  ${APP_SESSION_PUBLIC_KEY:/run/secrets/auth_session_public.pem}
#    qr-public-key-file:       ${APP_QR_PUBLIC_KEY:/run/secrets/qr_public.pem}
#    # Key IDs (kid) used in JWT headers (optional)
#    session-kid: "session-key-1"
