server:
  port: ${PORT:8087}

spring:
  # =========================
  # MONGODB
  # =========================
  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      url: ${REDIS_URL}

  # =========================
  # KAFKA (REDPANDA)
  # =========================
  kafka:
    bootstrap-servers: ${REDPANDA_BOOTSTRAP_SERVERS}

    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="${REDPANDA_USERNAME:}"
        password="${REDPANDA_PASSWORD:}";

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# =========================
# INVENTORY SERVICE CONFIG
# =========================
inventory:
  service:
    base-url: ${INVENTORY_SERVICE_URL}